apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.appName}}-{{.Values.envName}}-config
  namespace: {{.Values.namespace}}
data:
  HOST: {{.Values.host}}
  PORT: {{.Values.servicePort}}
  PUBLIC_URL: {{.Values.publicUrl}}
  LOG_LEVEL: {{.Values.logLevel}}
  LOG_STYLE: {{.Values.logStyle}}
  ADMIN_EMAIL: {{.Values.adminEmail}}
  ADMIN_PASSWORD: {{.Values.adminPassword}}
  DB_CLIENT: {{.Values.dbClient}}
  DB_HOST: {{.Values.dbHost}}
  DB_PORT: {{.Values.dbPort}}
  DB_USER: {{.Values.dbUser}}
  DB_PASSWORD: {{.Values.dbPassword}}
  DB_DATABASE: {{.Values.dbDatabase}}
  RATE_LIMITER_ENABLED: {{.Values.rateLimiterEnabled}}
  RATE_LIMITER_POINTS: {{.Values.rateLimiterPoints}}
  RATE_LIMITER_DURATION: {{.Values.rateLimiterDuration}}
  RATE_LIMITER_STORE: {{.Values.rateLimiterStore}}
  CACHE_ENABLED: {{.Values.cacheEnabled}}
  CACHE_TTL: {{.Values.cacheTTL}}
  CACHE_NAMESPACE: {{.Values.cacheNamespace}}
  CACHE_AUTO_PURGE: {{.Values.cacheAutoPurge}}
  CACHE_STORE: {{.Values.cacheStore}}
  ASSETS_CACHE_TTL: {{.Values.assetsCacheTTL}}
  STORAGE_LOCATIONS: {{.Values.storageLocations}}
  STORAGE_LOCAL_DRIVER: {{.Values.storageLocalDriver}}
  STORAGE_LOCAL_ROOT: {{.Values.storageLocalRoot}}
  STORAGE_S3_DRIVER: {{.Values.storageS3Driver}}
  STORAGE_S3_KEY: {{.Values.storageS3Key}}
  STORAGE_S3_SECRET: {{.Values.storageS3Secret}}
  STORAGE_S3_ENDPOINT: {{.Values.storageS3Endpoint}}
  STORAGE_S3_BUCKET: {{.Values.storageS3Bucket}}
  STORAGE_S3_REGION: {{.Values.storageS3Region}}
  KEY: {{.Values.key}}
  SECRET: {{.Values.secret}}
  ACCESS_TOKEN_TTL: {{.Values.accessTokenTTL}}
  REFRESH_TOKEN_TTL: {{.Values.refreshTokenTTL}}
  REFRESH_TOKEN_COOKIE_SECURE: {{.Values.refreshTokenCookieSecure}}
  REFRESH_TOKEN_COOKIE_SAME_SITE: {{.Values.refreshTokenCookieSameSite}}
  REFRESH_TOKEN_COOKIE_NAME: {{.Values.refreshTokenCookieName}}
  CONTENT_SECURITY_POLICY_DIRECTIVES_SCRIPT_SRC: {{.Values.contentSecurityPolicyDirectivesScriptSrc}}
  CONTENT_SECURITY_POLICY_DIRECTIVES_IMG_SRC: {{.Values.contentSecurityPolicyDirectivesImgSrc}}
  CORS_ENABLED: {{.Values.corsEnabled}}
  CORS_ORIGIN: {{.Values.corsOrigin}}
  CORS_METHODS: {{.Values.corsMethods}}
  CORS_ALLOWED_HEADERS: {{.Values.corsAllowedHeaders}}
  CORS_EXPOSED_HEADERS: {{.Values.corsExposedHeaders}}
  CORS_CREDENTIALS: {{.Values.corsCredentials}}
  CORS_MAX_AGE: {{.Values.corsMaxAge}}
  EXTENSIONS_PATH: {{.Values.extensionsPath}}
  EXTENSIONS_AUTO_RELOAD: {{.Values.extensionsAutoReload}}
  EMAIL_FROM: {{.Values.emailFrom}}
  EMAIL_TRANSPORT: {{.Values.emailTransport}}
  EMAIL_SENDMAIL_NEW_LINE: {{.Values.emailSendmailNewLine}}
  EMAIL_SENDMAIL_PATH: {{.Values.emailSendmailPath}}